import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './../components/Navbar/Navbar';
import Footer from './../components/footer/Footer';
import SideBar from './../components/sideBar/SideBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex flex-col md:flex-row">
          <div className="m-25">
            <SideBar className="md:w-64 xl:w-80" />
          </div>
          <div className="flex-1 m-20 min-h-[55vh]">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
